#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

echo "--- Applying test environment variables"
export DISABLE_SPRING="true"
export RAILS_ENV="test"
set -a
source .env
set +a

echo "--- Installing dependencies"
bundle install

echo "+++ Running tests"
bin/rspec
